// Static image imports (`import photo from "@/public/home/x.jpg"`) are typed by
// Next's image declarations. Those normally arrive via next-env.d.ts, which is
// gitignored and only generated by `next dev` / `next build` — so CI's
// typecheck, which runs before any build, could not resolve them. Referencing
// the declarations here, in a committed file, makes `tsc --noEmit` pass on a
// clean checkout.
/// <reference types="next/image-types/global" />
